// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdGR4T9-LuRIXafvwzZKyhIH4-obpqhfI',
    appId: '1:789554119624:android:4ef5803301233ffebc76fd',
    messagingSenderId: '789554119624',
    projectId: 'lookout-noob',
    storageBucket: 'lookout-noob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsshozjCpp8FDI3CFZ5HTKSaV383RErN0',
    appId: '1:789554119624:ios:3a3291ad412589b9bc76fd',
    messagingSenderId: '789554119624',
    projectId: 'lookout-noob',
    storageBucket: 'lookout-noob.appspot.com',
    iosClientId: '789554119624-475f5hi9rh7un630es38idg3lv8e10o7.apps.googleusercontent.com',
    iosBundleId: 'com.noob.lookout',
  );
}
